name: Build and Deploy train-ticket-reservation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build & Test with Maven
        run: mvn clean package

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-file
          path: target/*.war

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build     # <-- ensures artifact is available

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: war-file
          path: ./war

      - name: Deploy to DEV Tomcat
        env:
          URL: ${{ secrets.TOMCAT_URL_DEV }}
          USER: ${{ secrets.TOMCAT_USER_DEV }}
          PASS: ${{ secrets.TOMCAT_PASS_DEV }}
          WAR_FILE: ./war/*.war
        run: |
          echo "Checking Tomcat Manager access..."
          curl -v -u "$USER:$PASS" "$URL/list"

          echo "Deploying WAR file..."
          curl -v -u "$USER:$PASS" --fail --show-error -T $WAR_FILE \
            "$URL/deploy?path=/train-ticket-reservation&update=true"
     
  deploy-TEST:
     runs-on: ubuntu-latest
     needs: build     # <-- ensures artifact is available

     steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: war-file
          path: ./war

      - name: Deploy to TEST Tomcat
        env:
          URL: ${{ secrets.TOMCAT_URL_TEST }}
          USER: ${{ secrets.TOMCAT_USER_TEST }}
          PASS: ${{ secrets.TOMCAT_PASS_TEST }}
          WAR_FILE: ./war/*.war
        run: |
          echo "Checking Tomcat Manager access..."
          curl -v -u "$USER:$PASS" "$URL/list"

          echo "Deploying WAR file..."
          curl -v -u "$USER:$PASS" --fail --show-error -T $WAR_FILE \
            "$URL/deploy?path=/train-ticket-reservation&update=true" 

  deploy-PRE-PROD:
      runs-on: ubuntu-latest
      needs: build     # <-- ensures artifact is available

      steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: war-file
          path: ./war

      - name: Deploy to PRE-PROD Tomcat
        env:
          URL: ${{ secrets.TOMCAT_URL_PRE_PROD }}
          USER: ${{ secrets.TOMCAT_USER_PRE_PROD }}
          PASS: ${{ secrets.TOMCAT_PASS_PRE_PROD }}
          WAR_FILE: ./war/*.war
        run: |
          echo "Checking Tomcat Manager access..."
          curl -v -u "$USER:$PASS" "$URL/list"

          echo "Deploying WAR file..."
          curl -v -u "$USER:$PASS" --fail --show-error -T $WAR_FILE \
            "$URL/deploy?path=/train-ticket-reservation&update=true" 

  deploy-PROD:
      runs-on: ubuntu-latest
      needs: build     # <-- ensures artifact is available

      steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: war-file
          path: ./war

      - name: Deploy to PRE-PROD Tomcat
        env:
          URL: ${{ secrets.TOMCAT_URL_PROD }}
          USER: ${{ secrets.TOMCAT_USER_PROD }}
          PASS: ${{ secrets.TOMCAT_PASS_PROD }}
          WAR_FILE: ./war/*.war
        run: |
          echo "Checking Tomcat Manager access..."
          curl -v -u "$USER:$PASS" "$URL/list"

          echo "Deploying WAR file..."
          curl -v -u "$USER:$PASS" --fail --show-error -T $WAR_FILE \
            "$URL/deploy?path=/train-ticket-reservation&update=true" 

